### ISSUE TITLE
Namenode fails to start.

### ISSUE THREAD

**Issue by wadujj** [hortonworks/structor#36]
I am using the default (out of the box) settings. When i do vagrant up, I get the following error on the console

`==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 16/07/28 20:28:36 INFO blockmanagement.BlockManager: dfs.block.access.token.enable=true
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 16/07/28 20:28:36 INFO blockmanagement.BlockManager: dfs.block.access.key.update.interval=600 min(s), dfs.block.access.token.lifetime=600 min(s), dfs.encrypt.data.transfer.algorithm=null
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 16/07/28 20:28:36 ERROR namenode.NameNode: Failed to start namenode.
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: java.lang.InternalError
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 	at sun.security.ec.SunEC.initialize(Native Method)
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 	at sun.security.ec.SunEC.access$000(SunEC.java:49)
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 	at sun.security.ec.SunEC$1.run(SunEC.java:61)
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 	at sun.security.ec.SunEC$1.run(SunEC.java:58)
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 	at java.security.AccessController.doPrivileged(Native Method)
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 	at sun.security.ec.SunEC.<clinit>(SunEC.java:58)
==> nn: Notice: /Stage[main]/Hdfs_namenode/Exec[namenode-format]/returns: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
`

**Comment by alanfgates** [comment]
I think the security certificates in our box are old and have expired.  If you do a 'yum upgrade' in the box and then re-run the 'hadoop namenode -format' command it works.  I'll look into getting a more recent box version so that we get valid security certificates.
