### ISSUE TITLE
HDFS issues with secure cluster

### ISSUE THREAD

**Issue by jmaron** [hortonworks/structor#7]
Seeing these exceptions during client interactions with HDFS on secure 3 node cluster:

2014-07-25 18:56:09,667 [main] WARN  hdfs.DFSClient - Failed to connect to /240.0.0.12:1019 for block, add to deadNodes and continue. java.io.EOFException: Premature EOF: no length prefix available
java.io.EOFException: Premature EOF: no length prefix available
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:1987)
	at org.apache.hadoop.hdfs.RemoteBlockReader2.newBlockReader(RemoteBlockReader2.java:395)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReader(BlockReaderFactory.java:786)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:665)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:325)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:567)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:790)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:837)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:186)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.readFully(ZipArchiveInputStream.java:584)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:176)
	at org.apache.slider.common.tools.SliderUtils.getApplicationResourceInputStream(SliderUtils.java:1443)
	at org.apache.slider.providers.agent.AgentUtils.getApplicationMetainfo(AgentUtils.java:39)
	at org.apache.slider.providers.agent.AgentClientProvider.getApplicationTags(AgentClientProvider.java:201)
	at org.apache.slider.client.SliderClient.launchApplication(SliderClient.java:822)
	at org.apache.slider.client.SliderClient.startCluster(SliderClient.java:703)
	at org.apache.slider.client.SliderClient.actionThaw(SliderClient.java:1782)
	at org.apache.slider.client.SliderClient.runService(SliderClient.java:230)
	at org.apache.slider.core.main.ServiceLauncher.launchService(ServiceLauncher.java:186)
	at org.apache.slider.core.main.ServiceLauncher.launchServiceRobustly(ServiceLauncher.java:474)
	at org.apache.slider.core.main.ServiceLauncher.launchServiceAndExit(ServiceLauncher.java:405)
	at org.apache.slider.core.main.ServiceLauncher.serviceMain(ServiceLauncher.java:629)
	at org.apache.slider.Slider.main(Slider.java:49)

**Comment by omalley** [comment]
We bumped this up to 256 in 0902514f.

**Comment by Parthi10** [comment]
can you help me to solve this issue...

20/03/22 11:53:46 WARN DFSClient: Failed to connect to /172.31.45.122:50010 for block, add to deadNodes and continue. java.net.ConnectException: Connection timed out: no further information
java.net.ConnectException: Connection timed out: no further information
